baseURL: 'https://yo-goto.github.io/tools-for-one'
title: 'Tools for ONE'
theme: 'PaperMod'
languageCode: "ja-jp"
hasCJKLanguage: true

# è¨˜äº‹è¨­å®š
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
    minifyOutput: true

# hugoã®ãƒ¡ãƒ‹ãƒ¥ãƒ¼è¨­å®š
menu:
    main:
        - name: Search ğŸ”
          url: search/
          weight: 10
        - name: Archive ğŸ“œ
          url: archives
          weight: 20
        - name: Tags ğŸ·
          url: tags/
          weight: 30
        - name: Zenn ğŸ¤–
          url: "https://zenn.dev/estra"
          weight: 40

# ãƒ†ãƒ¼ãƒè¨­å®š
params:
  defaultTheme: dark
  DateFormat: "2006-01-02"
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  # ã‚µãƒ ãƒã‚¤ãƒ«ç”»åƒ
  cover:
      relative: false # when using page bundles set this to true

  homeInfoParams:
    Title: Tools for ONE
    Content: >
      - <img src="https://pbs.twimg.com/profile_banners/1218331225917509632/1633828032/1500x500" style="border-radius: 10px; filter: grayscale(100%); " />
      
      
      - 


      - ãƒŸãƒ‹ã‚µã‚¤ãƒˆã€Œ**ã‚¢ãƒ³ã‚­ãƒ¨ãƒªãƒã‚¸ãƒ¡ãƒ¨**ã€ã®ã‚¢ãƒ¼ã‚«ã‚¤ãƒ–ã‚’è¨˜è¼‰ã—ã¦ã„ã¾ã™

      - PADAone ã®å€‹äººãƒ–ãƒ­ã‚°ã¨ã—ã¦ãƒ„ãƒ¼ãƒ«ã‚„è‹±èªå­¦ç¿’ãªã©ã«ã¤ã„ã¦æ›¸ã„ã¦ã„ãäºˆå®šã§ã™


  # githubã§ã®ç·¨é›†ææ¡ˆ    
  editPost:
    URL: "https://github.com/yo-goto/anki-one/tree/main/content"
    Text: "Githubã§ä¿®æ­£"
    appendFilePath: true # to append file path to Edit link  
  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  socialIcons:
      - name: github
        url: "https://github.com/yo-goto"
      - name: twitter
        url: "https://twitter.com/pd1xx/"
      - name: zenn
        url: "https://zenn.dev/estra"

outputs:
    home:
        - HTML
        - RSS
        - JSON

markup:
    goldmark:
        renderer:
            unsafe: true        